[package]
name = "flash_card_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = { version = "1.0.0-beta.3", features = ["display", "from", "error"] }
nom = "7.1.3"
serde = { version = "1.0.188", features = ["derive"] }
